Lesson 1 and 2 Task 6 done
iamipheco/Lesson_1_and_2_Task_6_Anyaefiena_Ifechukwu pull request #1
Opened 2023-05-02 11:10 UTC by iamipheco

@promise-J
@ChidiPatrick
@OgJaykay
@Pieta9221
@MiniHack
@Melumm

I'm done with my Lesson 1 & 2 Task 4, Please Kindly Check it out.

2023-05-03 13:56 UTC, ChidiPatrick requested changes
Nice work. Please close all your input elements properly

2023-05-03 13:56 UTC, ChidiPatrick commented on docs/index.html
> +            <input type="checkbox" id="terms" name="terms" required>
Close your input elements at lines 47 and 49. <input/>

2023-05-04 04:47 UTC, iamipheco commented on docs/index.html
> +            <input type="checkbox" id="terms" name="terms" required>
> Close your input elements at lines 47 and 49.

All corrections have been made 
what is the next now

2023-05-04 09:13 UTC, ChidiPatrick approved these changes
Certified, you can now merge

2023-05-04 09:28 UTC, iamipheco commented
> Certified, you can now merge

Alright Thanks

2023-05-04 09:28 UTC, merged

2023-05-04 09:47 UTC, ChidiPatrick reviewed
Great! You can now merge

2023-05-04 10:05 UTC, OgJaykay reviewed
Good work👍👍👍.You can merge now